import java.awt.*;
import java.awt.image.*;
import java.io.FileOutputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.imageio.ImageIO;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
  private static final String IMAGE_OUT = "out";
  private static int count = 0;
  public static void main(final String[] args) throws Exception {
    Enigma enig = Parser.parse(Paths.get(args[0]));
    System.out.print(enig.processString(args[1]));
  }

  private static void renderingMain(final String[] args) throws Exception {
    if (args.length != 2) {
      System.err.println(
          "Expected two arguments: the config path and a string to encrypt.");
      System.err.println(args.length);
      return;
    }
    Draw d = new Draw(Parser.parse(Paths.get(args[0])), 1920, 1080);
    var imgs = d.processString(args[1]);
    for (RenderedImage img : imgs) {
      saveImageToFile(img);
    }
  }

  private static void saveImageToFile(RenderedImage img) {
    try {
      ImageIO.write(
          img, "jpeg",
          Paths.get(String.format("%s%d.jpg", IMAGE_OUT, count++)).toFile());
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
